services:
  - type: web
    name: zito-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run dev
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 8000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: BACKEND_PUBLIC_URL
        value: https://zito-cms-backend-new.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
